# This is a basic workflow to help you get started with Actions

name: invest on greeen adn future technology, (crypto that buy share and make solar adn renewarb energy,

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: i need someone to write a basic rypto that i total contrall but it has limit for how uch it will spit at the time, it only mine it self setting amount but no minors am controo the mining, then next will follow
    branches: [ master ] 
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:full online experies but am giving you my coin everytime your in  my site, only you mine coins for being in the site
  # This workflow contains a single job called "build"
  build:need front nad back gace of new social network put all freee movie and music and eduction, and everything someone does even sturdy am reward him my coin, i have total contalll about it.
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
